---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets2

spec:
  provider: aws
  secretObjects:
    - secretName: vr-creds
      type: Opaque
      data:
        - objectName: secret-token
          key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: /dev/RDS/ENDPOINT2
        objectType: secretsmanager
        jmesPath:
           - path: MY_API_TOKEN
             objectAlias: secret-token
