apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment1
  
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-deployment-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "admin-aws-secrets"
      containers:
      - name: demo-deployment
        image: nginx
### Start update
        env:
          - name: MY_PARAMETER
            valueFrom:
              secretKeyRef:
                name: my-k8s-secrets
                key: myParameter