---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets2
  
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data: 
    - objectName: secret-token
      key: SECRET_TOKEN
    - objectName: secret-token1
      key: SECRET_TOKEN1
  parameters:
    objects: |
      - objectName: /spikeseed/blog/myparameter1
        objectType: ssmparameter
        objectAlias: secret-token
      - objectName: newsecret
        objectType: ssmparameter
        objectAlias: secret-token1
